name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Prepare Deployment artifact
        run: |
          mkdir deploy
          cp -r build/* deploy/
          cp src/ public/ package.json package-lock.json start-server.sh deploy/
          tar -czvf deploy.tar.gz deploy/

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-artifact
          path: deploy.tar.gz
            

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download deployment artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy-artifact

      - name: SSH into EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Connect SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SERVER: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER >> ~/.ssh/known_hosts

      - name: Copy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SERVER: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null 
          scp -o StrictHostKeyChecking=no deploy.tar.gz $USERNAME@$SERVER:~/deploy.tar.gz 
          ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER "tar -xzvf deploy.tar.gz -C ~/ && cd ~/deploy && npm install && nohup node index.js > output.log 2>&1 &"
